### ISSUE TITLE
SSL Broken

### ISSUE THREAD

**Issue by XjCrazy09** [IgorAntun/node-chat#29]
Chat works great as HTTP, but when I change the config to:  

{
        "log": true,
        "port": 3000,
        "url": "/",
        "ssl": {
                "use": true,
                "key": '/privkey.key',
                "cert": "/cert.pem"
        },
        "readline": {
                "use": true,
                "prompt": "[--:--:--][CONSOLE] "
        }
}

I get the following error:  

[--:--:--][CONSOLE] fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/user/Documents/node-chat/app.js:369:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)

any ideas on how to fix this?  

Thanks in advance for the support!

**Comment by XjCrazy09** [comment]
I guess I copied the wrong config file.  Here is what I am actually using:  

        "log": true,
        "port": 3000,
        "url": "/",
        "ssl": {
                "use": true,
                "key": "privkey.key",
                "cert": "cert.crt"
        },
        "readline": {
                "use": true,
                "prompt": "[--:--:--][CONSOLE] "
        }
}

I used the double parenthesis instead of single quotes.
